import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MantineProvider } from "@mantine/core";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Discord Colored Text Generator</title>
      </head>
      <body className="min-h-screen bg-gray-900 text-white p-5"><MantineProvider withGlobalStyles withNormalizeCSS>
      {children}
    </MantineProvider></body>
    </html>
  );
}
